openapi: 3.1.0
info:
  title: Steadybit EventKit API
  version: 1.0.0
  license:
    name: MIT
    identifier: MIT
consumes:
  - application/json
produces:
  - application/json
components:
  schemas:
    EventListenerList:
      title: Event Listener List
      description: Lists all listeners that the platform/agent could call.
      type: object
      properties:
        eventListeners:
          type: array
          items:
            $ref: '#/components/schemas/EventListener'
          uniqueItems: true
      required:
        - eventListeners
    EventListener:
      title: Event Listener Description
      type: object
      properties:
        path:
          type: string
          description: Absolute path of the HTTP endpoint.
          pattern: ^/.*$
        method:
          description: HTTP method to use when calling the HTTP endpoint.
          $ref: '#/components/schemas/MutatingHttpMethod'
        restrictTo:
          type: string
          description: "If the agent is deployed as a daemonset in Kubernetes, should the discovery only be called from the leader agent? This can be helpful to avoid duplicate event listener calls every running agent. You may alternatively define that the listener should run only for Steadybit agents operating within the AWS agent mode (as defined by the `STEADYBIT_AGENT_MODE` Steadybit agent environment variable / the `agent.mode` Steadybit agent Helm chart value)."
          enum:
            - any
            - leader
            - aws
        listenTo:
          type: array
          description: >-
            List of event names that the event listener want to listen to. You may optionally define the special `*` event name to listen to all events.
          items:
            type: string
      required:
        - path
        - method
        - listenTo
    ListenResult:
      type: object
    DescribingEndpointReference:
      title: HTTP Endpoint Reference
      description: HTTP endpoint which the Steadybit platform/agent could communicate with.
      properties:
        path:
          description: Absolute path of the HTTP endpoint.
          type: string
          pattern: ^/.*$
        method:
          description: HTTP method to use when calling the HTTP endpoint.
          type: string
          enum:
            - get
      required:
        - path
        - method
    MutatingHttpMethod:
      type: string
      enum:
        - post
        - put
        - delete
    PrincipalType:
      type: string
      enum:
        - user
        - access_token
        - batch_job
    UserPrincipal:
      title: User Principal
      properties:
        username:
          type: string
          description: This is a unique identifier for the user.
        name:
          type: string
          description: A human-readable name for the user.
        email:
          type: string
        principalType:
          type: string
      required:
        - username
        - name
        - principalType
    AccessTokenType:
      type: string
      enum:
        - admin
        - team
    AccessTokenPrincipal:
      title: Access Token Principal
      properties:
        id:
          type: string
        name:
          type: string
          description: A human-readable name for the user.
        tokenType:
          $ref: '#/components/schemas/AccessTokenType'
        principalType:
          type: string
      required:
        - id
        - name
        - tokenType
        - principalType
    BatchPrincipal:
      title: Batch Principal
      properties:
        username:
          type: string
          description: This is a unique identifier for the user.
        principalType:
          type: string
      required:
        - username
        - principalType
    Principal:
      title: Principal
      description: The principal describes through which activity the action was triggered.
      anyOf:
        - $ref: '#/components/schemas/UserPrincipal'
        - $ref: '#/components/schemas/AccessTokenPrincipal'
        - $ref: '#/components/schemas/BatchPrincipal'
    Tenant:
      title: Tenant
      properties:
        key:
          type: string
        name:
          type: string
      required:
        - key
        - name
    Team:
      title: Team
      properties:
        id:
          type: string
        key:
          type: string
        name:
          type: string
      required:
        - id
        - key
        - name
    Environment:
      title: Environment
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    ExperimentExecution:
      title: Experiment Execution
      properties:
        experimentKey:
          type: string
        executionId:
          type: number
        name:
          type: string
        hypothesis:
          type: string
        preparedTime:
          type: string
          format: date-time
        startedTime:
          type: string
          format: date-time
        endedTime:
          type: string
          format: date-time
        state:
          type: string
          enum:
            - created
            - prepared
            - running
            - failed
            - completed
            - canceled
            - skipped
            - errored
        failureReason:
          type: string
        failureReasonDetails:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/ExperimentStepExecution'
      required:
        - experimentKey
        - executionId
        - name
        - hypothesis
        - preparedTime
        - startedTime
        - state
        - steps
    ExperimentStepExecution:
      title: Experiment Step Execution
      properties:
        id:
          type: string
          format: string
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
        type:
          type: string
          enum:
            - wait
            - action
        actionId:
          type: string
        actionName:
          type: string
        actionKind:
          type: string
          enum:
            - attack
            - check
            - load_test
            - other
        customLabel:
          type: string
        startedTime:
          type: string
          format: date-time
        endedTime:
          type: string
          format: date-time
        state:
          type: string
          enum:
            - created
            - prepared
            - running
            - failed
            - completed
            - canceled
            - skipped
            - errored
        targetExecutions:
          type: array
          items:
            $ref: '#/components/schemas/ExperimentStepExecutionTarget'
      required:
        - id
        - state
        - type
    ExperimentStepExecutionTarget:
      title: Experiment Step Execution Target
      properties:
        agentHostname:
          type: string
        targetName:
          type: string
        targetType:
            type: string
        targetAttributes:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      required:
        - agentHostname
        - targetName
        - targetType
        - targetAttributes
  requestBodies:
    EventRequestBody:
      title: Consume Event Request Body
      description: The HTTP request payload passed to the event listener.
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                format: string
                x-go-type: uuid.UUID
                x-go-type-import:
                  path: github.com/google/uuid
              eventName:
                type: string
              eventTime:
                type: string
                format: date-time
              principal:
                $ref: '#/components/schemas/Principal'
              tenant:
                $ref: '#/components/schemas/Tenant'
              team:
                $ref: '#/components/schemas/Team'
              environment:
                $ref: '#/components/schemas/Environment'
              experimentExecution:
                $ref: '#/components/schemas/ExperimentExecution'
              stepExecutionId:
                type: string
                format: string
                x-go-type: uuid.UUID
                x-go-type-import:
                  path: github.com/google/uuid
            required:
              - id
              - eventName
              - eventTime
              - principal
              - tenant
  responses:
    EventListenerListResponse:
      title: Event Listener List Response
      description: Response for the event list endpoint
      content:
        application/json:
          schema:
            anyOf:
              - $ref: '#/components/schemas/EventListenerList'