/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
	schemas: {
		/**
		 * Event Listener List
		 * @description Lists all listeners that the platform/agent could call.
		 */
		EventListenerList: {
			eventListeners: components['schemas']['EventListener'][];
		};
		/** Event Listener Description */
		EventListener: {
			/** @description Absolute path of the HTTP endpoint. */
			path: string;
			/** @description HTTP method to use when calling the HTTP endpoint. */
			method: components['schemas']['MutatingHttpMethod'];
			/**
			 * @description If the agent is deployed as a daemonset in Kubernetes, should the discovery only be called from the leader agent? This can be helpful to avoid duplicate event listener calls every running agent. You may alternatively define that the listener should run only for Steadybit agents operating within the AWS agent mode (as defined by the `STEADYBIT_AGENT_MODE` Steadybit agent environment variable / the `agent.mode` Steadybit agent Helm chart value).
			 * @enum {string}
			 */
			restrictTo?: 'any' | 'leader' | 'aws';
			/** @description List of event names that the event listener want to listen to. You may optionally define the special `*` event name to listen to all events. */
			listenTo: string[];
		};
		ListenResult: { [key: string]: unknown };
		/**
		 * HTTP Endpoint Reference
		 * @description HTTP endpoint which the Steadybit platform/agent could communicate with.
		 */
		DescribingEndpointReference: {
			/** @description Absolute path of the HTTP endpoint. */
			path: string;
			/**
			 * @description HTTP method to use when calling the HTTP endpoint.
			 * @enum {string}
			 */
			method: 'get';
		};
		/** @enum {string} */
		MutatingHttpMethod: 'post' | 'put' | 'delete';
		/** @enum {string} */
		PrincipalType: 'user' | 'access_token' | 'batch_job';
		/** User Principal */
		UserPrincipal: {
			/** @description This is a unique identifier for the user. */
			username: string;
			/** @description A human-readable name for the user. */
			name: string;
			email?: string;
			principalType: string;
		};
		/** @enum {string} */
		AccessTokenType: 'admin' | 'team';
		/** Access Token Principal */
		AccessTokenPrincipal: {
			id: string;
			/** @description A human-readable name for the user. */
			name: string;
			tokenType: components['schemas']['AccessTokenType'];
			principalType: string;
		};
		/** Batch Principal */
		BatchPrincipal: {
			/** @description This is a unique identifier for the user. */
			username: string;
			principalType: string;
		};
		/**
		 * Principal
		 * @description The principal describes through which activity the action was triggered.
		 */
		Principal: Partial<components['schemas']['UserPrincipal']> &
			Partial<components['schemas']['AccessTokenPrincipal']> &
			Partial<components['schemas']['BatchPrincipal']>;
		/** Tenant */
		Tenant: {
			key: string;
			name: string;
		};
		/** Team */
		Team: {
			id: string;
			key: string;
			name: string;
		};
		/** Environment */
		Environment: {
			id: string;
			name: string;
		};
		/** Experiment Execution */
		ExperimentExecution: {
			experimentKey: string;
			executionId: string;
			name: string;
			hypothesis: string;
			/** Format: date-time */
			preparedTime: string;
			/** Format: date-time */
			startedTime: string;
			/** Format: date-time */
			endedTime?: string;
			/** @enum {string} */
			state: 'created' | 'prepared' | 'running' | 'failed' | 'completed' | 'canceled' | 'skipped' | 'errored';
			failureReason?: string;
			failureReasonDetails?: string;
			variables: { [key: string]: string };
		};
	};
	responses: {
		/** Response for the event list endpoint */
		EventListenerListResponse: {
			content: {
				'application/json': Partial<components['schemas']['EventListenerList']>;
			};
		};
	};
	requestBodies: {
		/** The HTTP request payload passed to the event listener. */
		EventRequestBody: {
			content: {
				'application/json': {
					/** Format: string */
					id: string;
					eventName: string;
					/** Format: date-time */
					eventTime: string;
					principal: components['schemas']['Principal'];
					tenant: components['schemas']['Tenant'];
					team?: components['schemas']['Team'];
					environment?: components['schemas']['Environment'];
					experimentExecution?: components['schemas']['ExperimentExecution'];
				};
			};
		};
	};
}

export interface operations {}

export interface external {}
