// Package event_kit_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.1-0.20220629212257-2cf7fcf5b26d DO NOT EDIT.
package event_kit_api

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Defines values for DescribingEndpointReferenceMethod.
const (
	Get DescribingEndpointReferenceMethod = "get"
)

// Defines values for EventKitErrorStatus.
const (
	Errored EventKitErrorStatus = "errored"
	Failed  EventKitErrorStatus = "failed"
)

// Defines values for ExperimentExecutionState.
const (
	CANCELED  ExperimentExecutionState = "CANCELED"
	COMPLETED ExperimentExecutionState = "COMPLETED"
	CREATED   ExperimentExecutionState = "CREATED"
	ERRORED   ExperimentExecutionState = "ERRORED"
	FAILED    ExperimentExecutionState = "FAILED"
	PREPARED  ExperimentExecutionState = "PREPARED"
	RUNNING   ExperimentExecutionState = "RUNNING"
	SKIPPED   ExperimentExecutionState = "SKIPPED"
)

// Defines values for ExperimentExecutionTriggeredVia.
const (
	API      ExperimentExecutionTriggeredVia = "API"
	SCHEDULE ExperimentExecutionTriggeredVia = "SCHEDULE"
	USER     ExperimentExecutionTriggeredVia = "USER"
)

// Defines values for MutatingHttpMethod.
const (
	Delete MutatingHttpMethod = "delete"
	Post   MutatingHttpMethod = "post"
	Put    MutatingHttpMethod = "put"
)

// HTTP endpoint which the Steadybit platform/agent could communicate with.
type DescribingEndpointReference struct {
	// HTTP method to use when calling the HTTP endpoint.
	Method DescribingEndpointReferenceMethod `json:"method"`

	// Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// HTTP method to use when calling the HTTP endpoint.
type DescribingEndpointReferenceMethod string

// The environment is used to identify the environment that the user is currently interacting with.
type Environment struct {
	// The id of the environment. This is the unique identifier for the environment. The id is used to identify the environment in the platform.
	Id *string `json:"id,omitempty"`

	// The name of the environment. This name is used to identify the environment in the platform.
	Name *string `json:"name,omitempty"`
}

// An enhanced version of RFC 7807 Problem Details for HTTP APIs compliant response body for error scenarios
type EventKitError struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// * failed - The event listener has detected some failures, for example a failing test which has been implemented by the event listener. The event listener will be stopped, if this status is returned by the status endpoint. * errored - There was a technical error while executing the event listener. Will be marked as red in the platform. The event listener will be stopped, if this status is returned by the status endpoint.
	Status *EventKitErrorStatus `json:"status,omitempty"`

	// A short, human-readable summary of the problem type.
	Title string `json:"title"`

	// A URI reference that identifies the problem type.
	Type *string `json:"type,omitempty"`
}

// * failed - The event listener has detected some failures, for example a failing test which has been implemented by the event listener. The event listener will be stopped, if this status is returned by the status endpoint. * errored - There was a technical error while executing the event listener. Will be marked as red in the platform. The event listener will be stopped, if this status is returned by the status endpoint.
type EventKitErrorStatus string

// Provides details about a possible event listener, e.g., what configuration options it has,how to trigger the listener.
type EventListenerDescription struct {
	// Description for end-users to help them understand what the event listener is doing.
	Description string `json:"description"`

	// An icon that is used to identify your event listener in the ui. Needs to be a data-uri containing an image.
	Icon *string `json:"icon,omitempty"`

	// A technical ID that is used to uniquely identify this type of the event listener. You will typically want to use something like `org.example.my-fancy-listener`.
	Id string `json:"id"`

	// List of environmentVariables that should be included in the event
	IncludeEnvironmentVariables *[]string `json:"includeEnvironmentVariables,omitempty"`

	// A human-readable label for the event listener.
	Label string `json:"label"`

	// HTTP endpoint which the Steadybit platform/agent could communicate with.
	Listen MutatingEndpointReference `json:"listen"`

	// List of events that the event listener want to listen to.
	ListenTo *[]string `json:"listenTo,omitempty"`

	// The version of the event listener. Remember to increase the value everytime you update the definitions. The platform will ignore any definition changes with the same event listener version. We do recommend usage of semver strings.
	Version string `json:"version"`
}

// Lists all listeners that the platform/agent could call.
type EventListenerList struct {
	Actions *[]DescribingEndpointReference `json:"actions,omitempty"`
}

// The experiment execution is used to identify the experiment execution
type ExperimentExecution struct {
	// The time when the experiment execution was ended
	EndedTime *time.Time `json:"endedTime,omitempty"`

	// The id of the experiment execution
	ExecutionId *string `json:"executionId,omitempty"`

	// The key of the experiment
	ExperimentKey *string `json:"experimentKey,omitempty"`

	// The failure reason of the experiment execution
	FailureReason *string `json:"failureReason,omitempty"`

	// The failure reason details of the experiment execution
	FailureReasonDetails *string `json:"failureReasonDetails,omitempty"`

	// The hypothesis of the experiment execution. This hypothesis is used to identify the experiment execution in the platform.
	Hypothesis *string `json:"hypothesis,omitempty"`

	// The name of the experiment execution. This name is used to identify the experiment execution in the platform.
	Name *string `json:"name,omitempty"`

	// The time when the experiment execution was prepared
	PreparedTime *time.Time `json:"preparedTime,omitempty"`

	// The time when the experiment execution was started
	StartedTime *time.Time `json:"startedTime,omitempty"`

	// The state of the experiment execution
	State *ExperimentExecutionState `json:"state,omitempty"`

	// The trigger of the experiment execution
	TriggeredVia *ExperimentExecutionTriggeredVia `json:"triggeredVia,omitempty"`

	// The variables of the experiment execution
	Variables *map[string]string `json:"variables,omitempty"`
}

// The state of the experiment execution
type ExperimentExecutionState string

// The trigger of the experiment execution
type ExperimentExecutionTriggeredVia string

// ListenResult defines model for ListenResult.
type ListenResult = map[string]interface{}

// HTTP endpoint which the Steadybit platform/agent could communicate with.
type MutatingEndpointReference struct {
	Method MutatingHttpMethod `json:"method"`

	// Absolute path of the HTTP endpoint.
	Path string `json:"path"`
}

// MutatingHttpMethod defines model for MutatingHttpMethod.
type MutatingHttpMethod string

// The user principal is used to identify the user that is currently interacting with the platform.
type Principal struct {
	// The email address of the user. This email address is used to identify the user in the platform.
	Email *string `json:"email,omitempty"`

	// The name of the user. This name is used to identify the user in the platform.
	Name *string `json:"name,omitempty"`

	// The username of the user. This is the unique identifier for the user. The username is used to identify the user in the platform.
	Username *string `json:"username,omitempty"`
}

// The team is used to identify the team that the user is currently interacting with.
type Team struct {
	// The id of the team. This is the unique identifier for the team. The id is used to identify the team in the platform.
	Id *string `json:"id,omitempty"`

	// The key of the team. This is the unique identifier for the team. The key is used to identify the team in the platform.
	Key *string `json:"key,omitempty"`

	// The name of the team. This name is used to identify the team in the platform.
	Name *string `json:"name,omitempty"`
}

// The tenant is used to identify the tenant that the user is currently interacting with.
type Tenant struct {
	// The key of the tenant. This is the unique identifier for the tenant. The key is used to identify the tenant in the platform.
	Key *string `json:"key,omitempty"`

	// The name of the tenant. This name is used to identify the tenant in the platform.
	Name *string `json:"name,omitempty"`
}

// DescribeEventListenerResponse defines model for DescribeEventListenerResponse.
type DescribeEventListenerResponse struct {
	union json.RawMessage
}

// EventListenerListResponse defines model for EventListenerListResponse.
type EventListenerListResponse struct {
	union json.RawMessage
}

// EventListenerRequestBody defines model for EventListenerRequestBody.
type EventListenerRequestBody struct {
	// The environment is used to identify the environment that the user is currently interacting with.
	Environment *Environment `json:"environment,omitempty"`
	EventName   *string      `json:"eventName,omitempty"`
	EventTime   *time.Time   `json:"eventTime,omitempty"`

	// The experiment execution is used to identify the experiment execution
	ExperimentExecution *ExperimentExecution `json:"experimentExecution,omitempty"`
	Id                  *uuid.UUID           `json:"id,omitempty"`

	// The user principal is used to identify the user that is currently interacting with the platform.
	Principal *Principal `json:"principal,omitempty"`

	// The team is used to identify the team that the user is currently interacting with.
	Team *Team `json:"team,omitempty"`

	// The tenant is used to identify the tenant that the user is currently interacting with.
	Tenant *Tenant `json:"tenant,omitempty"`
}

func (t DescribeEventListenerResponse) AsEventListenerDescription() (EventListenerDescription, error) {
	var body EventListenerDescription
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *DescribeEventListenerResponse) FromEventListenerDescription(v EventListenerDescription) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t DescribeEventListenerResponse) AsEventKitError() (EventKitError, error) {
	var body EventKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *DescribeEventListenerResponse) FromEventKitError(v EventKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t DescribeEventListenerResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *DescribeEventListenerResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

func (t EventListenerListResponse) AsEventListenerList() (EventListenerList, error) {
	var body EventListenerList
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *EventListenerListResponse) FromEventListenerList(v EventListenerList) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t EventListenerListResponse) AsEventKitError() (EventKitError, error) {
	var body EventKitError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

func (t *EventListenerListResponse) FromEventKitError(v EventKitError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t EventListenerListResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventListenerListResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

type ParameterOption interface {}